kleveross/klever-model-registry

- build/extract/torchscript/Dockerfile
- build/modeljob-operator/Dockerfile
- config/samples/modeljobs_v1alpha1_torchscript_extract.yaml
- scripts/extract/extract.py
Fixes #
Reference to #
```release-note
NONE
```
> feat: Support TorchScript

- build/extract/onnx/Dockerfile
- config/samples/modeljobs_v1alpha1_onnx_extract.yaml
- scripts/extract/extractor/extract_onnx.py
Fixes #
Reference to #
```release-note
NONE
```
> feat: Support ONNX

- build/extract/caffe2/Dockerfile
- build/extract/graphdef/Dockerfile
- build/extract/pmml/Dockerfile
- build/extract/pmml/application.conf
- config/samples/modeljobs_v1alpha1_caffe2_extract.yaml
- config/samples/modeljobs_v1alpha1_graphdef_extract.yaml
- config/samples/modeljobs_v1alpha1_pmml_extract.yaml
- scripts/extract/extract.py
- scripts/extract/extractor/extract_graphdef.py
- scripts/extract/extractor/extract_pmml.py
- scripts/shell/run.sh
Fixes #
Reference to #
```release-note
NONE
```
> feat: Support PMML & GraphDef & Caffe2 extract

- cmd/modeljob-operator/app/options/options.go
- cmd/modeljob-operator/app/server.go
- cmd/modeljob-operator/main.go
- pkg/version/version.go
Fixes #
Reference to #
```release-note
NONE
```
> feat: Add version flag

- pkg/controllers/errors.go
- pkg/controllers/reconcile.go
- scripts/shell/run.sh
Fixes #
https://github.com/caicloud/temp-model-registry/issues/10
Reference to #
```release-note
NONE
```
> feat: Set error message when modeljob error

- pkg/registry/server/event/controller.go
- pkg/registry/server/event/route.go
Fixes #
Reference to #
```release-note
NONE
```
> feat: Add event api

- go.mod
- go.sum
- pkg/apis/modeljob/v1alpha1/modeljob_types.go
- pkg/controllers/reconcile.go
- pkg/controllers/utils.go
- vendor/modules.txt
Fixes #
Reference to #
```release-note
NONE
```
> fix(operator): Fix modeljob status

- .gitignore
- README.md
Signed-off-by: Ce Gao <gaoce@caicloud.io>
Fixes #
Reference to #
```release-note
NONE
```
> feat: Update community section

- build/klever-model-registry/Dockerfile
- pkg/registry/resource/container/logs.go
- pkg/registry/resource/logs/logs.go
- pkg/registry/server/log/log.go
- pkg/registry/server/server.go
Fixes #
Reference to #
```release-note
NONE
```
> feat: Add log api

- pkg/registry/resource/container/logs.go
Fixes #
https://github.com/kleveross/temp-model-registry/issues/38
Reference to #
```release-note
NONE
```
> feat(log): Use Pod log subresource

- README.md
- README_zh.md
Signed-off-by: Ce Gao <gaoce@caicloud.io>
Update README in Chinese and English
Fixes #
Reference to #
```release-note
NONE
```
> feat: Update readme

- pkg/registry/apis/api.go
Fixes #
Reference to #
```release-note
NONE
```
> feat: Replace apis with api of url prefix

- .travis.yml
- README.md
- pkg/controllers/initialization.go
- pkg/controllers/modeljob_controller_test.go
- pkg/controllers/reconcile.go
- pkg/controllers/reconcile_test.go
- pkg/controllers/suite_test.go
- pkg/controllers/utils.go
- pkg/controllers/utils_test.go
- testutil/testutil.go
Fixes #
Reference to #
```release-note
NONE
```
> feat: Add modeljob operator unit tests

- README_zh.md
Fixes #
Reference to #
```release-note
NONE
```
> feat: Add badge for chinese README

- manifests/klever-modeljob-operator/templates/deployment.yaml
- manifests/klever-modeljob-operator/values.yaml
- scripts/shell/run.sh
fix(env): add domain ip env and modify run shell
Fixes #
Reference to #
```release-note
NONE
```
> fix(env): add domain ip env and modify run shell

- pkg/registry/apis/api.go
- pkg/registry/apis/v1alpha1/descriptors/harbor.go
- pkg/registry/harbor/harbor.go
Fixes #
Reference to #
```release-note
NONE
```
> feat: Refactor api

- Makefile
- cmd/klever-model-registry/main.go
- nirvana.yaml
- pkg/registry/apis/api.go
- pkg/registry/apis/v1alpha1/descriptors/descriptor.go
- pkg/registry/apis/v1alpha1/descriptors/modeljob.go
- pkg/registry/filters/filters.go
- pkg/registry/modifiers/modifiers.go
Stop using the default config for future customization and API documentation generation
Fixes #
Reference to #
```release-note
NONE
```
> chore(*): adjust the config of the nirvana server

- Makefile
- docs/api/api.v1alpha1.json
* tweak for GOFLAGS config in Makefile
* update API docs to latest
Fixes #
Reference to #
```release-note
NONE
```
> chore(Makefile): tweak for GOFLAGS config

- pkg/registry/apis/v1alpha1/descriptors/modeljob.go
- pkg/registry/event/event_test.go
- pkg/registry/modeljob/modeljob.go
- pkg/registry/modeljob/modeljob_test.go
fix(api): add namespace in registry api
Fixes #
Reference to #
```release-note
NONE
```
> fix(api): add namespace in registry api

- README.md
- README_zh.md
- hack/boilerplate.go.txt
- manifests/examples/modeljobs_v1alpha1_caffe2_extract.yaml
- manifests/examples/modeljobs_v1alpha1_caffe_convert.yaml
- manifests/examples/modeljobs_v1alpha1_caffe_extract.yaml
- manifests/examples/modeljobs_v1alpha1_graphdef_extract.yaml
- manifests/examples/modeljobs_v1alpha1_h5_convert.yaml
- manifests/examples/modeljobs_v1alpha1_h5_extract.yaml
- manifests/examples/modeljobs_v1alpha1_mxnet_convert.yaml
- manifests/examples/modeljobs_v1alpha1_mxnet_extract.yaml
- manifests/examples/modeljobs_v1alpha1_onnx_extract.yaml
- manifests/examples/modeljobs_v1alpha1_pmml_extract.yaml
- manifests/examples/modeljobs_v1alpha1_savedmodel_extract.yaml
- manifests/examples/modeljobs_v1alpha1_torchscript_extract.yaml
- manifests/klever-model-registry/templates/deployment.yaml
- manifests/klever-model-registry/templates/service.yaml
- manifests/klever-model-registry/values.yaml
- manifests/klever-modeljob-operator/templates/cluster-role-binding.yaml
- manifests/klever-modeljob-operator/templates/deployment.yaml
- manifests/klever-modeljob-operator/templates/preset-image-configmap.yaml
- manifests/klever-modeljob-operator/templates/secret.yaml
- manifests/klever-modeljob-operator/values.yaml
- scripts/shell/run.sh
Fixes #
https://github.com/kleveross/klever-model-registry/issues/61
Reference to #
```release-note
NONE
```
> feat(deploy): Support deploy Harbor by helm

- pkg/common/consts.go
- pkg/registry/client/client.go
- pkg/registry/models/files.go
- pkg/registry/models/types.go
- pkg/registry/models/util.go
- pkg/registry/models/util_test.go
Fixes #
Reference to #
```release-note
NONE
```
> feat(*): Support more params when upload model

- cmd/klever-model-registry/main.go
- go.mod
- go.sum
- pkg/apis/modeljob/v1alpha1/modeljob_types.go
- pkg/common/consts.go
- pkg/controllers/initialization.go
- pkg/controllers/utils_test.go
- pkg/registry/apis/v1alpha1/descriptors/event.go
- pkg/registry/apis/v1alpha1/descriptors/log.go
- pkg/registry/apis/v1alpha1/descriptors/modeljob.go
- pkg/registry/client/client.go
- pkg/registry/event/event.go
- pkg/registry/event/event_suite_test.go
- pkg/registry/event/event_test.go
- pkg/registry/log/log.go
- pkg/registry/modeljob/modeljob.go
- pkg/registry/modeljob/modeljob_suite_test.go
- pkg/registry/modeljob/modeljob_test.go
- pkg/registry/models/files.go
Fixes https://github.com/kleveross/klever-model-registry/issues/29
Reference to #
```release-note
NONE
```
> feat: Using cache to list/get resource

- pkg/registry/errors/errors.go
- pkg/registry/event/event.go
- pkg/registry/log/log.go
- pkg/registry/modeljob/modeljob.go
- pkg/registry/models/files.go
Fixes https://github.com/kleveross/klever-model-registry/issues/25
Reference to #
```release-note
NONE
```
> feat: Unified error code format

- pkg/controllers/utils.go
Fixes #
Reference to #
```release-note
NONE
```
> feat: Set relayout false for ormb-storage-initializer

- build/extract/tensorrt/Dockerfile
- scripts/extract/extractor/__init__.py
- scripts/extract/extractor/extract_tensorrt.py
Fixes #
Reference to #
```release-note
NONE
```
> feat: support tensorrt extract

- .gitignore
- Makefile
- cmd/klever-model-registry/main.go
- go.mod
- pkg/common/consts.go
- pkg/registry/apis/api.go
- pkg/registry/apis/v1alpha1/descriptors/harbor.go
- pkg/registry/client/client.go
- pkg/registry/config/types.go
- pkg/registry/harbor/harbor.go
- pkg/registry/models/util_test.go
Signed-off-by: Ce Gao <gaoce.gaoc@bytedance.com>
- Avoid init before nirvana
- Make build by default in Makefile
Fixes #
Reference to #
/cc @simon-cj 
```release-note
NONE
```
> misc: Optimize the code

- .github/workflows/main.yml
Signed-off-by: Ce Gao <gaoce.gaoc@bytedance.com>
Fixes #
Reference to #
```release-note
NONE
```
> feat: Use github actions to run ut and e2e test

- pkg/registry/serving/composer.go
Fixes #
Reference to #
```release-note
NONE
```
> feat: Support inference's traffic diversion

- pkg/registry/serving/composer_test.go
- pkg/registry/serving/serving.go
- pkg/registry/serving/serving_suite_test.go
Fixes #
Reference to #
```release-note
NONE
```
> feat: Add serving unittest

- pkg/registry/serving/composer.go
Fixes https://github.com/kleveross/klever-model-registry/issues/78
Reference to #
```release-note
NONE
```
> feat: Support GPU scheduling

- pkg/controllers/utils.go
Fixes #
Reference to #
```release-note
NONE
```
> fix: Set modeljob's job BackoffLimit 0

- cmd/model-registry/main.go
- go.sum
- pkg/registry/apis/api.go
- pkg/registry/apis/v1alpha1/descriptors/harbor.go
- pkg/registry/harbor/artifacts.go
- pkg/registry/harbor/harbor.go
Fixes #
Reference to #
```release-note
NONE
```
> feat: Auto create extract modeljob when ormb push

- README.md
- README_zh.md
- manifests/model-registry/templates/deployment.yaml
- manifests/model-registry/values.yaml
- pkg/registry/apis/v1alpha1/descriptors/harbor.go
- pkg/registry/harbor/harbor.go
Fixes #
Reference to #
```release-note
NONE
```
> fix: Fix ormb can not push bug

- pkg/registry/apis/v1alpha1/descriptors/model.go
- pkg/registry/models/files.go
- pkg/registry/models/types.go
- pkg/registry/models/util.go
- pkg/util/utils.go
This PR add project name as a  parameter in model upload and download function.
Fixes #92 
Reference to #
```release-note
NONE
```
> fix(model): add project parameter in model upload and download

- pkg/registry/apis/v1alpha1/descriptors/log.go
Change log to logs by following the RESTFul specification
Fixes #
Reference to #
```release-note
NONE
```
> fix(api): change log to logs by following the RESTFul specification

- pkg/registry/apis/v1alpha1/descriptors/event.go
- pkg/registry/apis/v1alpha1/descriptors/harbor.go
- pkg/registry/apis/v1alpha1/descriptors/log.go
- pkg/registry/apis/v1alpha1/descriptors/modeljob.go
- pkg/registry/apis/v1alpha1/descriptors/serving.go
fix(api): fulfill api information and add some comments
Fixes #
Reference to #
```release-note
NONE
```
> fix(api): fulfill api information and add some comments

- pkg/registry/serving/composer.go
- pkg/registry/serving/composer_test.go
Fixes https://github.com/kleveross/klever-model-registry/issues/81
Reference to #
```release-note
NONE
```
> feat: Support gRPC and HTTP protocols

- pkg/registry/models/util.go
Fixes https://github.com/kleveross/klever-model-registry/issues/100
Reference to #
```release-note
NONE
```
> fix: Fix upload model if model zip is model.zip

- pkg/registry/modeljob/modeljob_test.go
Fixes #
Reference to #
```release-note
NONE
```
> fix: Fix import bug

- build/convert/caffemodel_to_netdef/Dockerfile
- build/convert/h5_to_savedmodel/Dockerfile
- build/convert/mxnetparams_to_onnx/Dockerfile
- build/extract/caffe/Dockerfile
- build/extract/caffe2/Dockerfile
- build/extract/graphdef/Dockerfile
- build/extract/h5/Dockerfile
- build/extract/mxnetparams/Dockerfile
- build/extract/onnx/Dockerfile
- build/extract/pmml/Dockerfile
- build/extract/savedmodel/Dockerfile
- build/extract/tensorrt/Dockerfile
- build/extract/torchscript/Dockerfile
Fixes #
Reference to #
```release-note
NONE
```
> feat: Update ormb version in Dockerfile

- pkg/registry/harbor/artifacts.go
- pkg/registry/modeljob/util.go
- pkg/registry/models/files.go
- testutil/integration/registry_test.go
Fixes #
Reference to #
```release-note
NONE
```
> feat: Auto extract model when upload model in the UI

- manifests/modeljob-operator/templates/deployment.yaml
- manifests/modeljob-operator/values.yaml
- pkg/controllers/consts.go
- pkg/controllers/modeljob_controller_test.go
- pkg/controllers/utils.go
- pkg/controllers/utils_test.go
Fixes #
Reference to #
```release-note
NONE
```
> feat: Support auto extract after convert

- build/extract/mxnetparams/Dockerfile
Fixes #
Reference to #
```release-note
NONE
```
> fix: Fix mxnet Dockerfile

- PROJECT
Fixes #
Reference to #
```release-note
NONE
```
> misc: Update PROJECT

- manifests/modeljob-operator/templates/deployment.yaml
- manifests/modeljob-operator/values.yaml
- pkg/controllers/consts.go
- pkg/controllers/utils.go
Fixes #
Reference to #
```release-note
NONE
```
> feat(controller): Support set SchedulerName

- README.md
- README_zh.md
- docs/installation/installation.md
- docs/installation/installation_zh.md
Fixes #
Reference to #
```release-note
NONE
```
> feat(docs): Add seldon core install docs

- pkg/registry/apis/v1alpha1/descriptors/comparison.go
- pkg/registry/comparison/comparison.go
- pkg/registry/comparison/types.go
- pkg/registry/harbor/artifacts.go
Feat(comparison): add model compasrison from ormb metadata
TODO: unit test
Fixes #
Reference to #
/cc @gaocegege @simon-cj 
```release-note
NONE
```
> Feat(comparison): add model comparison from ormb metadata

- OWNERS
Chore(owners): add FogDong
Fixes #
Reference to #
```release-note
NONE
```
> Chore(owners): add FogDong

- pkg/registry/apis/v1alpha1/descriptors/harbor.go
- pkg/registry/comparison/comparison.go
- pkg/registry/comparison/comparison_test.go
- pkg/registry/harbor/artifacts.go
- pkg/registry/harbor/harbor.go
- pkg/registry/harbor/harbor_fake.go
Feat(test): add comparison test
Fixes #
Reference to #
```release-note
NONE
```
> Feat(test): add comparison test

- README.md
- README_zh.md
- docs/docs_zh/installation.md
- docs/installation.md
Fixes https://github.com/kleveross/klever-model-registry/issues/126
Reference to #
```release-note
NONE
```
> fix(docs): Update installation manual

- pkg/registry/harbor/artifacts.go
- pkg/registry/modeljob/util.go
- pkg/registry/models/files.go
- pkg/registry/serving/composer.go
- scripts/serving/wrapper/entrypoint.sh
- scripts/serving/wrapper/openscoring.sh
- scripts/serving/wrapper/preprocessor.py
- scripts/serving/wrapper/utils/get_model.py
Fixes #
Reference to #
```release-note
NONE
```
> fix: Fix serving model dir structure

- manifests/model-registry/templates/deployment.yaml
- pkg/registry/serving/composer.go
- pkg/registry/serving/composer_test.go
For Clever，every container must be set resource， otherwise will occor error， and can not create pod successfully.
Fixes #
Reference to #
```release-note
NONE
```
> feat: Support set model initializer container resource

- .github/workflows/main.yml
Fixes #
Reference to #
```release-note
NONE
```
> [fix] Fix the test coverage

- pkg/registry/serving/composer.go
- None GPU schedule must set NVIDIA_VISIBLE_DEVICES enviroment.
- Support SchedulerName for serving.
Fixes #
Reference to #
```release-note
NONE
```
> fix: Fix GPU schedule

- Makefile
- docs/docs_zh/installation.md
- docs/installation.md
- manifests/model-registry/templates/deployment.yaml
- manifests/model-registry/templates/service.yaml
- manifests/model-registry/values.yaml
- manifests/modeljob-operator/templates/preset-image-configmap.yaml
- manifests/modeljob-operator/templates/secret.yaml
- manifests/modeljob-operator/values.yaml
- scripts/installation/install.sh
Fixes #
Reference to #
```release-note
NONE
```
> feat(installation): Update installation

- README.md
- README_zh.md
- docs/docs_zh/installation.md
- docs/installation.md
- scripts/installation/install.sh
Fixes #
Reference to #
```release-note
NONE
```
> feat(docs): Update Install docs

- pkg/registry/comparison/comparison.go
- pkg/registry/comparison/comparison_test.go
Fixes #
Reference to #
```release-note
NONE
```
> feat: Add more unit tests

- cmd/model-registry/main.go
- pkg/registry/serving/composer.go
- pkg/registry/serving/composer_test.go
- testutil/integration/serving_test.go
we want to pass resource(cpu, mem, gpu) information by SeldonDeployment.ComponentSpecs, not using SeldonDeployment.Graph.Parameter.
Fixes #
Reference to #
```release-note
NONE
```
> fix(serving): Update serving resources

- pkg/registry/serving/composer_test.go
Fixes #
Reference to #
```release-note
NONE
```
> fix(e2e): Fix e2e tests

- .github/workflows/publish.yml
Fixes #
Reference to #
```release-note
NONE
```
> feat(ci): Add publish action

- .github/workflows/publish.yml
Fixes #
Reference to #
```release-note
NONE
```
> fix: Fix publish action

- .github/workflows/publish.yml
- build/extract/caffe/Dockerfile
- build/extract/pmml/Dockerfile
- build/serving/openscoring/Dockerfile
- manifests/model-registry/Chart.yaml
- manifests/model-registry/values.yaml
- manifests/modeljob-operator/Chart.yaml
- manifests/modeljob-operator/templates/preset-image-configmap.yaml
Fixes #
Reference to #
```release-note
NONE
```
> feat(action): Add publish action

- .github/workflows/publish.yml
Fixes #
Reference to #
```release-note
NONE
```
> fix(action): Fix public action

- build/extract/h5/Dockerfile
Fixes #
Reference to #
```release-note
NONE
```
> fix(dockerfile): Fix H5 extract Dockerfile

- build/extract/caffe2/Dockerfile
- build/extract/mxnetparams/Dockerfile
- build/extract/torchscript/Dockerfile
Fixes #
Reference to #
```release-note
NONE
```
> fix: Fix dockerfile

- build/extract/caffe2/Dockerfile
Fixes #
Reference to #
```release-note
NONE
```
> fix: Fix github action

- build/extract/caffe/Dockerfile
Fixes #
Reference to #
```release-note
NONE
```
> fix: Fix caffe dockerfile base image

- README.md
- README_zh.md
- manifests/examples/serving/graphdef-sdep.yaml
- manifests/examples/serving/header-diversion-sdep.yaml
- manifests/examples/serving/netdef-sdep.yaml
- manifests/examples/serving/onnx-sdep.yaml
- manifests/examples/serving/pecent-diversion-sdep.yaml
- manifests/examples/serving/pmml-sdep.yaml
- manifests/examples/serving/savedmodel-sdep.yaml
- manifests/examples/serving/tensorrt-sdep.yaml
- manifests/examples/serving/torchscript-sdep.yaml
- manifests/model-registry/values.yaml
Fixes #
Reference to #
```release-note
NONE
```
> chore(*): Update docker image tag

- build/serving/tensorrt/Dockerfile
- pkg/registry/serving/composer.go
- scripts/serving/tensorrt/entrypoint.sh
Fixes #
Reference to #
```release-note
NONE
```
> feat(serving): Upgrade triton server to v20.08

- docs/README.md
- docs/docs_zh/README.md
- pkg/registry/apis/v1alpha1/descriptors/serving.go
- pkg/registry/serving/serving.go
- testutil/integration/serving_test.go
Add serving update interface
Fixes #
Reference to #
```release-note
NONE
```
> feat (KLV-11): HPA support via seldonDeployment update

- pkg/registry/serving/composer.go
- pkg/registry/serving/composer_test.go
Fixes #
Reference to #
```release-note
NONE
```
> feat(serving): Support custom image

- go.mod
- go.sum
- pkg/registry/apis/v1alpha1/descriptors/harbor.go
- vendor/github.com/caicloud/nirvana/definition/definition.go
- vendor/github.com/caicloud/nirvana/log/log.go
- vendor/github.com/caicloud/nirvana/service/builder.go
- vendor/github.com/caicloud/nirvana/service/context.go
- vendor/github.com/caicloud/nirvana/service/executor.go
- vendor/github.com/caicloud/nirvana/service/utils.go
- vendor/github.com/caicloud/nirvana/utils/api/definitions.go
- vendor/modules.txt
Fixes #
Reference to #
```release-note
NONE
```
> chore(*): use service.WrapHTTPHandler in proxy APIs

- scripts/serving/wrapper/preprocessor.py
- scripts/serving/wrapper/utils/config_generator.py
- scripts/serving/wrapper/utils/get_model.py
- scripts/serving/wrapper/utils/help_functions.py
- scripts/serving/wrapper/utils/model_formatter.py
Fix(scripts): fix python lint
Fixes #
Reference to #
```release-note
NONE
```
> Fix(scripts): fix python lint

- build/serving/mlserver/Dockerfile
- pkg/apis/modeljob/v1alpha1/modeljob_types.go
- pkg/registry/serving/composer.go
- scripts/serving/mlserver/entrypoint.sh
- scripts/serving/wrapper/preprocessor.py
- scripts/serving/wrapper/utils/help_functions.py
- scripts/serving/wrapper/utils/model_formatter.py
Feat(serving): add spark mllib model serving
Fixes #
Reference to #
/cc @simon-cj @gaocegege @Thrimbda 
```release-note
NONE
```
> Feat(serving): add spark mllib model serving

- manifests/model-registry/values.yaml
- pkg/registry/serving/composer.go
- pkg/registry/serving/composer_test.go
Fixes #
Reference to #
/cc @gaocegege @Thrimbda @FogDong 
```release-note
NONE
```
> Fix(serving): fix create serving bug

- cmd/model-registry/main.go
- pkg/registry/apis/v1alpha1/descriptors/pod.go
- pkg/registry/pod/pod.go
Fixes #
Reference to #
```release-note
NONE
```
> feat: Add get pod instance

- manifests/modeljob-operator/templates/cluster-role.yaml
- pkg/controllers/reconcile.go
- pkg/registry/apis/v1alpha1/descriptors/event.go
- pkg/registry/apis/v1alpha1/descriptors/modeljob.go
- pkg/registry/event/event.go
- pkg/registry/event/event_test.go
- pkg/registry/harbor/harbor.go
- pkg/registry/modeljob/modeljob.go
- pkg/registry/modeljob/modeljob_test.go
- pkg/registry/modeljob/util.go
Fixes #
Reference to #
```release-note
NONE
```
> chore(*): Solve some issue by docking with the frontend

- manifests/examples/serving/graphdef-sdep.yaml
- manifests/examples/serving/header-diversion-sdep.yaml
- manifests/examples/serving/netdef-sdep.yaml
- manifests/examples/serving/onnx-sdep.yaml
- manifests/examples/serving/pecent-diversion-sdep.yaml
- manifests/examples/serving/pmml-sdep.yaml
- manifests/examples/serving/savedmodel-sdep.yaml
- manifests/examples/serving/tensorrt-sdep.yaml
- manifests/examples/serving/torchscript-sdep.yaml
- manifests/model-registry/Chart.yaml
- manifests/model-registry/values.yaml
- manifests/modeljob-operator/Chart.yaml
- manifests/modeljob-operator/templates/preset-image-configmap.yaml
- scripts/installation/install.sh
- scripts/installation/patch/istio/istio-1.2.2/install/kubernetes/helm/istio/charts/gateways/templates/role.yaml
- scripts/installation/patch/istio/istio-1.2.2/install/kubernetes/helm/istio/charts/gateways/templates/rolebindings.yaml
Release v0.2.0
Fixes #
Reference to #
```release-note
Release v0.2.0
```
> feat(release): release v0.2.0

- .github/workflows/e2e.yml
- .github/workflows/main.yml
- .github/workflows/publish.yml
Upgrade github action command
Fixes #
Reference to #
```release-note
Upgrade github action command
```
> chore(*): Upgrade github action command

- build/extract/caffe/Dockerfile
Update caffe Dockerfile
Fixes #
Reference to #
```release-note
Update caffe Dockerfile
```
> chore(*): Update caffe Dockerfile

- build/serving/mlserver/Dockerfile
Fix(mlserver): fix mlserver dockerfile
Fixes #
Reference to #
/cc @simon-cj 
```release-note
NONE
```
> Fix(mlserver): fix mlserver dockerfile

- .github/workflows/e2e.yml
- build/model-registry/Dockerfile
- cmd/modeljob-operator/app/server.go
- crds/kleveross.io_modeljobs.yaml
- pkg/controllers/suite_test.go
Feat(crd): init model job crd when run the controller
Fixes #
Reference to #
/cc @simon-cj 
```release-note
NONE
```
> Feat(crd): init model job crd when run the controller

- scripts/installation/install.sh
Feat(install): add klever-web in install scripts
Fixes #
Reference to #
/cc @simon-cj 
```release-note
NONE
```
> Feat(install): add klever-web in install scripts

- build/model-registry/Dockerfile
- build/modeljob-operator/Dockerfile
Fix(Dockerfile): fix operator and registry dockerfile to add crd file in image
Fixes #
Reference to #
/cc @simon-cj 
```release-note
NONE
```
> Fix(Dockerfile): fix operator and registry dockerfile to add crd file in image

- manifests/modeljob-operator/templates/preset-image-configmap.yaml
- manifests/modeljob-operator/values.yaml
Update modeljob operator helm
Fixes #
Reference to #
/cc @judgeeeeee 
```release-note
Update modeljob operator helm
```
> chore(*): update modeljob operator helm

- pkg/registry/apis/v1alpha1/descriptors/serving.go
- pkg/registry/serving/composer.go
- pkg/registry/serving/serving.go
- testutil/integration/serving_test.go
1. We require to specify graph.name and seldonPodSpec.Metadata.Name , and they are consistent, so we don't use model's tag to name it here.
2. We will check whether volumes and volumemounts are entered. If it exists, we will use it, otherwise the default configuration will be used.
3. We consider that a predictor may be added when update serving, so will recompose the new predictor.
4. Triton inference server provides functionality specifically for health checks, so we updated the probe.
Fixes #
Reference to #
```release-note
1. We require to specify graph.name and seldonPodSpec.Metadata.Name , and …
```
> fix(serving):fix bug of create and update api of serving

- manifests/modeljob-operator/templates/preset-image-configmap.yaml
- manifests/modeljob-operator/values.yaml
- scripts/installation/install.sh
- scripts/installation/patch/harbor-helm/templates/core/core-dpl.yaml
Fix install scripts
Fixes #
Reference to #
```release-note
Fix install scripts
```
> fix(scripts): fix install scripts

- .github/PULL_REQUEST_TEMPLATE.md
Update github template
Fixes #
Reference to #
/cc @codeflitting @FogDong 
```release-note
update github template
```
> chore(*): update github template

- pkg/controllers/utils.go
- pkg/registry/serving/composer.go
- pkg/registry/serving/composer_test.go
- pkg/registry/serving/serving_suite_test.go
/kind bug
/area serving
Fix serving model URI bug, using default domain to fill model URI.
Fixes #
Reference to #
/cc @codeflitting @FogDong 
```release-note
Fix serving model URI bug
```
> fix(serving): fix serving model uri params

- Makefile
/kind bug
fix  caffe build bug
Fixes #
Reference to #
/cc @simon-cj 
```release-note
NONE
```
> fix(build): fix caffe build

- scripts/extract/extractor/extract_caffe.py
- scripts/extract/extractor/extract_graphdef.py
- scripts/extract/extractor/extract_keras.py
- scripts/extract/extractor/extract_mxnet.py
- scripts/extract/extractor/extract_onnx.py
- scripts/extract/extractor/extract_pmml.py
- scripts/extract/extractor/extract_savedmodel.py
- scripts/extract/extractor/extract_tensorrt.py
- scripts/extract/extractor/extract_torchscript.py
- scripts/serving/wrapper/preprocessor.py
- scripts/serving/wrapper/utils/config_generator.py
/kind feature
/area model
/area serving
update optype -> opType in signature
Fixes #
Reference to #
/cc @simon-cj @songzhiwei7 
```release-note
update dtype -> dType in signature
update optype -> opType in signature
```
> feat(*):update  signature 

- scripts/convert/converter/base_convert.py
/kind feature
/area model
support convert read inputs from env
Fixes #
Reference to #
/cc @FogDong @simon-cj 
```release-note
support convert read inputs from env
```
> feat(*): support convert read inputs from env

- manifests/modeljob-operator/values.yaml
- pkg/controllers/consts.go
/kind bug
/area model
Fix image tag & some consts
Fixes #
Reference to #
```release-note
Fix image tag & some consts
```
> fix(controller): fix image tag & some consts

- build/convert/caffemodel_to_netdef/Dockerfile
- scripts/convert/converter/base_convert.py
/kind bug
/area model
fix caffe convert bug
Fixes #
Reference to #
/cc @simon-cj 
```release-note
None
```
> fix(convert): fix caffe extract scripts bugs

- scripts/convert/converter/base_convert.py
- scripts/serving/wrapper/preprocessor.py
/kind feature
/area serving
/area model
Support env for scripts
Fixes #
Reference to #
```release-note
Support env for scripts
```
> feat(scripts): support env for scripts

- build/convert/caffemodel_to_netdef/Dockerfile
- scripts/convert/converter/__init__.py
- scripts/convert/converter/base_convert.py
/kind bug
/area model
Fixes #
Reference to #
/cc @simon-cj @FogDong 
```release-note
NONE
```
> fix(converter): dockerfile and add check for input

- pkg/controllers/utils.go
/kind bug
/area model
Inject env to job
Fixes #
Reference to #
```release-note
Inject env to job
```
> fix(job): inject env to job

- manifests/modeljob-operator/templates/deployment.yaml
/kind bug
/area serving
**What this PR does / why we need it**: Fix(env): fix env name in model job deployment
Fixes #
Reference to #
/cc @simon-cj 
```release-note
Fix(env): fix env name in model job deployment
```
> Fix(env): fix env name in model job deployment

- testutil/integration/serving_test.go
**What this PR does / why we need it**: 
Add e2e test cases for serving
Fixes #
Reference to #
/cc @simon-cj 
```release-note
Add e2e test cases for serving
```
> test(E2ETest): Add e2e test cases for serving

- README.md
- README_zh.md
- scripts/installation/install-k8s-1.19.sh
/kind documentation
Fixes #
Reference to #
/cc @codeflitting @FogDong @judgeeeeee 
```release-note
Update readme documents
```
> chore(doc): update README

- .github/workflows/publish.yml
- Makefile
- build/convert/caffemodel_to_netdef/Dockerfile
- build/convert/h5_to_savedmodel/Dockerfile
- build/convert/mxnetparams_to_onnx/Dockerfile
- build/convert/netdef_to_onnx/Dockerfile
- build/extract/caffemodel/Dockerfile
- build/extract/graphdef/Dockerfile
- build/extract/h5/Dockerfile
- build/extract/mxnetparams/Dockerfile
- build/extract/netdef/Dockerfile
- build/extract/onnx/Dockerfile
- build/extract/pmml/Dockerfile
- build/extract/savedmodel/Dockerfile
- build/extract/tensorrt/Dockerfile
- build/extract/torchscript/Dockerfile
- scripts/shell/test.sh
/kind test
/area model
add model extract/convert docker e2e test
Fixes #
Reference to #
/cc @simon-cj 
```release-note
Add model extract/convert docker e2e test
```
> feat(test): add model extract/convert e2e test

- scripts/convert/converter/base_convert.py
- scripts/extract/extract.py
- scripts/shell/test.sh
/kind bug
/area cicd
Update e2e test caffe2 model path
Fixes #
Reference to #
/cc @simon-cj 
```release-note
Update e2e test caffe2 model path
```
> fix(test): update yaml pkg && caffe2 model path

- pkg/registry/serving/composer.go
/kind bug
/area serving
fix bug of container's volumes and volumeMounts cannot be covered
Fixes #
Reference to #
/cc @simon-cj @FogDong 
```release-note
fix bug of container's volumes and volumeMounts cannot be covered
```
> fix(serving):fix bug of container's volumes and volumeMounts cannot be covered

- pkg/registry/serving/composer.go
/kind feature
/area serving
must ensure that all subpaths of volumemount use the default rule
Fixes #
Reference to #
```release-note
None
```
> feat(serving): must ensure that all subpaths of volumemount use the default rule

- pkg/registry/serving/composer.go
/kind feature
/kind serving
Feat(compose): skip compose init container when users have one
Fixes #
Reference to #
/cc @simon-cj @songzhiwei7 
```release-note
skip compose init container when users have one
```
> Feat(compose): skip compose init container when users have one

- scripts/extract/extractor/extract_graphdef.py
/kind bug
Fixes #
Reference to #
/cc @simon-cj 
```release-note
NONE
```
> fix(extract):graphdef dtype key error

- scripts/serving/wrapper/preprocessor.py
/kind bug
/area serving
fix bug of modelDir's name must be "model"
Fixes #
Reference to #
/cc @simon-cj @judgeeeeee 
```release-note
fix bug of modelDir's name must be "model"
```
> fix(serving):fix bug of modelDir's name must be "model"

- scripts/serving/wrapper/utils/model_formatter.py
/area model
/kind bug
fix graphdef formater
Fixes #
Reference to #
```release-note
fix graphdef formater
```
> fix(scripts): fix graphdef formater

- .github/workflows/e2e.yml
- Makefile
- cmd/modeljob-operator/app/server.go
- crds/kleveross.io_modeljobs.yaml
- manifests/model-registry/Chart.yaml
- manifests/model-registry/values.yaml
- manifests/modeljob-operator/Chart.yaml
- manifests/modeljob-operator/crds/kleveross.io_modeljobs.yaml
- manifests/modeljob-operator/templates/deployment.yaml
- manifests/modeljob-operator/values.yaml
/kind bug
/area model
Fixes #
Reference to #
```release-note
upgrade crd
```
> feat(crd): upgrade crd

- pkg/controllers/consts.go
- pkg/controllers/reconcile.go
- pkg/controllers/utils.go
/area model
refactor event & log
Fixes #
Reference to #
```release-note
refactor event & log
```
> refactor(controller): refactor event & log

- scripts/shell/run.sh
/area model
/kind cleanup
remove echo ormb password
Fixes #
Reference to #
/cc @FogDong 
```release-note
remove echo ormb password
```
> fix(scripts): remove echo password

- scripts/extract/extractor/extract_savedmodel.py
/kind bug
Fixes #
Reference to #
/cc @simon-cj 
```release-note
NONE
```
> fix(savedmodel): inputs/outputs name in signature

- go.mod
- go.sum
- vendor/github.com/seldonio/seldon-core/operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
- vendor/github.com/seldonio/seldon-core/operator/constants/constants.go
- vendor/modules.txt
/kind feature
/area serving
update vendor
Fixes #
Reference to #
```release-note
update vendor
```
> feat(vendor): update vendor

- pkg/controllers/consts.go
- pkg/controllers/reconcile.go
- pkg/controllers/reconcile_test.go
/kind feature
/area model
When pull image error, set message "failed to pull image".
When resource is insufficient， set message like  “'0/11 nodes are available: 10 Insufficient cpu, 9 Insufficient memory”
Fixes #
Reference to #
```release-note
add error message detail
```
> feat(operator): add error message detail

- Makefile
/kind feature
upgrade ormb to v0.0.10
Fixes #
Reference to #
```release-note
upgrade ormb to v0.0.10
```
> chore(*): upgrade ormb to v0.0.10

- manifests/model-registry/Chart.yaml
- manifests/model-registry/values.yaml
- manifests/modeljob-operator/Chart.yaml
- manifests/modeljob-operator/values.yaml
release v0.3.0-alpha.2
Fixes #
Reference to #
```release-note
release v0.3.0-alpha.2
```
> feat(release): release v0.3.0-alpha.2

- scripts/serving/wrapper/preprocessor.py
/kind bug
/area serving
fix bug of remove old folder when restart serving's pod
Fixes #
Reference to #
```release-note
fix bug of remove old folder when restart serving's pod
```
> fix(serving): fix bug of remove old folder when restart serving's pod

- pkg/controllers/consts.go
- pkg/controllers/reconcile.go
- pkg/controllers/reconcile_test.go
/kind bug
refactor error message
Fixes #
Reference to #
```release-note
refactor error message
```
> refactor(controller): refactor error message

- pkg/controllers/reconcile.go
/kind bug
/area controller
fix modeljob status
Fixes #
Reference to #
```release-note
None
```
> fix(model): fix modeljob status

- scripts/serving/wrapper/preprocessor.py
/kind bug
/area serving
cancel determine whether ormbfile.yaml file and model folder exist
Fixes #
Reference to #
```release-note
cancel determine whether ormbfile.yaml file and model folder exist
```
> fix(serving): cancel determine whether ormbfile.yaml file and model folder exist

- build/serving/tritonserver/Dockerfile
/kind upgrade
/area serving
Fixes https://github.com/triton-inference-server/server/issues/1988
Reference to #
```release-note
Changed: update triton from v20.08 to v20.09
```
> feat(triton): update v20.08 to v20.09

- pkg/registry/serving/composer.go
- scripts/serving/wrapper/preprocessor.py
/kind bug
/area serving
1. run failed because the old_model_path is undefined
2. no need to set the default env when container is custom
Fixes #
Reference to #
```release-note
fix bug of serving userContainer's image and env
```
> fix(serving): fix bug of serving userContainer's image and env

- scripts/convert/converter/base_convert.py
/kind bug
/area model
Fixes #
Reference to #
/cc @judgeeeeee 
```release-note
None
```
> fix(scripts): do not set signature for conversion
